In [1]:
from pandas import  *
from seaborn import *
from matplotlib.pyplot import *
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import LabelEncoder

In [2]:
df=read_csv('cricket1.csv')
df

Outlook Temperature Humidity  Windy Play Cricket
0      Sunny         Hot     High  False           No
1      Sunny         Hot     High   True           No
2   Overcast         Hot     High  False          Yes
3      Rainy        Mild     High  False          Yes
4      Rainy        Cool   Normal  False          Yes
5      Rainy        Cool   Normal   True           No
6   Overcast        Cool   Normal   True          Yes
7      Sunny        Mild     High  False           No
8      Sunny        Cool   Normal  False          Yes
9      Rainy        Mild   Normal  False          Yes
10     Sunny        Mild   Normal   True          Yes
11  Overcast        Mild     High   True          Yes
12  Overcast         Hot   Normal  False          Yes
13     Rainy        Mild     High   True           No

In [3]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [4]:

# Assuming 'df' is your DataFrame containing multiple categorical columns to encode
encoded_col = ['Outlook', 'Temperature', 'Humidity', 'Windy', 'Play Cricket']

# Apply LabelEncoder to multiple columns
df[encoded_col] = df[encoded_col].apply(lambda col: le.fit_transform(col))


In [5]:
x=df.iloc[: , 0:4]
x

Outlook  Temperature  Humidity  Windy
0         2            1         0      0
1         2            1         0      1
2         0            1         0      0
3         1            2         0      0
4         1            0         1      0
5         1            0         1      1
6         0            0         1      1
7         2            2         0      0
8         2            0         1      0
9         1            2         1      0
10        2            2         1      1
11        0            2         0      1
12        0            1         1      0
13        1            2         0      1

In [6]:
y=df[['Play Cricket']]
y

Play Cricket
0              0
1              0
2              1
3              1
4              1
5              0
6              1
7              0
8              1
9              1
10             1
11             1
12             1
13             0

--------------LOGISTIC REGRESSION----------------------

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=16)

In [8]:
from sklearn.linear_model import LogisticRegression
l=LogisticRegression()


In [9]:

l=LogisticRegression()
l.fit(x_train,y_train)

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [10]:
l.score(x_train,y_train)

0.8888888888888888

In [11]:
l.score(x_test,y_test)     #test is more imp. / crucial than train accuracy

1.0

In [12]:
l.predict([[2,1,0,0]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

-------------------SVM---------------------

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [14]:
from sklearn.svm import SVC
s=SVC()           #kernel = 'rbf'
s.fit(x_train,y_train)

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [15]:
s.score(x_train,y_train)

0.8888888888888888

In [16]:
s.score(x_test,y_test) #test is more imp.

1.0

In [17]:
s.predict([[2,1,0,0]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([0])

-----------------GAUSSIAN NAIVE BIAS --------------------

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=10)

In [19]:
from sklearn.naive_bayes import GaussianNB
g=GaussianNB()
g.fit(x_train,y_train)

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [20]:
g.score(x_train,y_train)

0.8888888888888888

In [21]:
g.score(x_test,y_test) #test is more imp.

1.0

In [22]:
g.predict([[2,1,0,0]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


array([0])

-----------DECISION TREES(2nd MOST POWERFUL)--------------------------------

In [23]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=128)

In [24]:
from sklearn.tree import DecisionTreeClassifier
d=DecisionTreeClassifier(criterion='entropy') #d=DecisionTreeClassifier(), default criterion is gini.
d.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [25]:
d.score(x_train,y_train)

1.0

In [26]:
d.score(x_test,y_test)

1.0

In [27]:
d.predict([[2,1,0,0]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0])

--------------RANDOM FOREST(MOST POWERFUL)--------------

In [39]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [40]:
from sklearn.ensemble import RandomForestClassifier
r=RandomForestClassifier(n_estimators=200)
r.fit(x_train,y_train)

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier(n_estimators=200)

In [41]:
r.score(x_train,y_train)

1.0

In [42]:
r.score(x_test,y_test)

1.0

In [43]:
r.predict([[2,1,0,0]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0])

In [33]:
###
'''import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

# Assuming 'x' and 'y' are defined with your dataset

max_train_accuracy = 0.0  # Initialize maximum training accuracy
best_train_random_state = 0  # Initialize variable to store the random state of the best training accuracy
max_test_accuracy = 0.0  # Initialize maximum testing accuracy
best_test_random_state = 0  # Initialize variable to store the random state of the best testing accuracy

for i in range(1, 1000):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=i)
    r=LogisticRegression()
    r.fit(x_train,y_train)  # Train the model
    train_score = r.score(x_train, y_train)  # Calculate accuracy on the training set
    test_score = r.score(x_test, y_test)  # Calculate accuracy on the test set
    
    # Check for the maximum training accuracy
    if train_score > max_train_accuracy:
        max_train_accuracy = train_score
        best_train_random_state = i

    # Check for the maximum testing accuracy
    if test_score > max_test_accuracy:
        max_test_accuracy = test_score
        best_test_random_state = i

print(f"The maximum training accuracy within the range of random states is: {max_train_accuracy} achieved with random state: {best_train_random_state}")
print(f"The maximum testing accuracy within the range of random states is: {max_test_accuracy} achieved with random state: {best_test_random_state}")
'''

'import numpy as np\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.svm import SVC\n\n# Assuming \'x\' and \'y\' are defined with your dataset\n\nmax_train_accuracy = 0.0  # Initialize maximum training accuracy\nbest_train_random_state = 0  # Initialize variable to store the random state of the best training accuracy\nmax_test_accuracy = 0.0  # Initialize maximum testing accuracy\nbest_test_random_state = 0  # Initialize variable to store the random state of the best testing accuracy\n\nfor i in range(1, 1000):\n    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=i)\n    r=LogisticRegression()\n    r.fit(x_train,y_train)  # Train the model\n    train_score = r.score(x_train, y_train)  # Calculate accuracy on the training set\n    test_score = r.score(x_test, y_test)  # Calculate accuracy on the test set\n    \n    # Check for the maximum training accuracy\n    if train_score > max_train_accuracy:\n        max_train_accuracy = tr

In [34]:
###
'''import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

# Assuming 'x' and 'y' are defined with your dataset

max_train_accuracy = 0.0  # Initialize maximum training accuracy
best_train_random_state = 0  # Initialize variable to store the random state of the best training accuracy
max_test_accuracy = 0.0  # Initialize maximum testing accuracy
best_test_random_state = 0  # Initialize variable to store the random state of the best testing accuracy

for i in range(1, 1000):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=i)
    r=SVC()
    r.fit(x_train,y_train)  # Train the model
    train_score = r.score(x_train, y_train)  # Calculate accuracy on the training set
    test_score = r.score(x_test, y_test)  # Calculate accuracy on the test set
    
    # Check for the maximum training accuracy
    if train_score > max_train_accuracy:
        max_train_accuracy = train_score
        best_train_random_state = i

    # Check for the maximum testing accuracy
    if test_score > max_test_accuracy:
        max_test_accuracy = test_score
        best_test_random_state = i

print(f"The maximum training accuracy within the range of random states is: {max_train_accuracy} achieved with random state: {best_train_random_state}")
print(f"The maximum testing accuracy within the range of random states is: {max_test_accuracy} achieved with random state: {best_test_random_state}")
'''

'import numpy as np\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.svm import SVC\n\n# Assuming \'x\' and \'y\' are defined with your dataset\n\nmax_train_accuracy = 0.0  # Initialize maximum training accuracy\nbest_train_random_state = 0  # Initialize variable to store the random state of the best training accuracy\nmax_test_accuracy = 0.0  # Initialize maximum testing accuracy\nbest_test_random_state = 0  # Initialize variable to store the random state of the best testing accuracy\n\nfor i in range(1, 1000):\n    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=i)\n    r=SVC()\n    r.fit(x_train,y_train)  # Train the model\n    train_score = r.score(x_train, y_train)  # Calculate accuracy on the training set\n    test_score = r.score(x_test, y_test)  # Calculate accuracy on the test set\n    \n    # Check for the maximum training accuracy\n    if train_score > max_train_accuracy:\n        max_train_accuracy = train_score\n    

In [35]:
'''
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
# Assuming 'x' and 'y' are defined with your dataset

max_train_accuracy = 0.0  # Initialize maximum training accuracy
best_train_random_state = 0  # Initialize variable to store the random state of the best training accuracy
max_test_accuracy = 0.0  # Initialize maximum testing accuracy
best_test_random_state = 0  # Initialize variable to store the random state of the best testing accuracy

for i in range(1, 1000):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=i)
    r=GaussianNB()
    r.fit(x_train,y_train)  # Train the model
    train_score = r.score(x_train, y_train)  # Calculate accuracy on the training set
    test_score = r.score(x_test, y_test)  # Calculate accuracy on the test set
    
    # Check for the maximum training accuracy
    if train_score > max_train_accuracy:
        max_train_accuracy = train_score
        best_train_random_state = i

    # Check for the maximum testing accuracy
    if test_score > max_test_accuracy:
        max_test_accuracy = test_score
        best_test_random_state = i

print(f"The maximum training accuracy within the range of random states is: {max_train_accuracy} achieved with random state: {best_train_random_state}")
print(f"The maximum testing accuracy within the range of random states is: {max_test_accuracy} achieved with random state: {best_test_random_state}")
'''

'\nimport numpy as np\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.svm import SVC\nfrom sklearn.naive_bayes import MultinomialNB\nfrom sklearn.naive_bayes import GaussianNB\n# Assuming \'x\' and \'y\' are defined with your dataset\n\nmax_train_accuracy = 0.0  # Initialize maximum training accuracy\nbest_train_random_state = 0  # Initialize variable to store the random state of the best training accuracy\nmax_test_accuracy = 0.0  # Initialize maximum testing accuracy\nbest_test_random_state = 0  # Initialize variable to store the random state of the best testing accuracy\n\nfor i in range(1, 1000):\n    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=i)\n    r=GaussianNB()\n    r.fit(x_train,y_train)  # Train the model\n    train_score = r.score(x_train, y_train)  # Calculate accuracy on the training set\n    test_score = r.score(x_test, y_test)  # Calculate accuracy on the test set\n    \n    # Check for the maximum training 

In [36]:
###
'''import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

# Assuming 'x' and 'y' are defined with your dataset

max_train_accuracy = 0.0  # Initialize maximum training accuracy
best_train_random_state = 0  # Initialize variable to store the random state of the best training accuracy
max_test_accuracy = 0.0  # Initialize maximum testing accuracy
best_test_random_state = 0  # Initialize variable to store the random state of the best testing accuracy

for i in range(1, 1000):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=i)
    r=DecisionTreeClassifier()
    r.fit(x_train,y_train)  # Train the model
    train_score = r.score(x_train, y_train)  # Calculate accuracy on the training set
    test_score = r.score(x_test, y_test)  # Calculate accuracy on the test set
    
    # Check for the maximum training accuracy
    if train_score > max_train_accuracy:
        max_train_accuracy = train_score
        best_train_random_state = i

    # Check for the maximum testing accuracy
    if test_score > max_test_accuracy:
        max_test_accuracy = test_score
        best_test_random_state = i

print(f"The maximum training accuracy within the range of random states is: {max_train_accuracy} achieved with random state: {best_train_random_state}")
print(f"The maximum testing accuracy within the range of random states is: {max_test_accuracy} achieved with random state: {best_test_random_state}")
'''

'import numpy as np\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.svm import SVC\n\n# Assuming \'x\' and \'y\' are defined with your dataset\n\nmax_train_accuracy = 0.0  # Initialize maximum training accuracy\nbest_train_random_state = 0  # Initialize variable to store the random state of the best training accuracy\nmax_test_accuracy = 0.0  # Initialize maximum testing accuracy\nbest_test_random_state = 0  # Initialize variable to store the random state of the best testing accuracy\n\nfor i in range(1, 1000):\n    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=i)\n    r=DecisionTreeClassifier()\n    r.fit(x_train,y_train)  # Train the model\n    train_score = r.score(x_train, y_train)  # Calculate accuracy on the training set\n    test_score = r.score(x_test, y_test)  # Calculate accuracy on the test set\n    \n    # Check for the maximum training accuracy\n    if train_score > max_train_accuracy:\n        max_train_accuracy 

In [37]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

# Assuming 'x' and 'y' are defined with your dataset

# Initialize variables
max_train_accuracy = 0.0
best_train_random_state = 0
max_test_accuracy = 0.0
best_test_random_state = 0
best_n_estimators = 0

# Loop over n_estimators
for i in range(1, 100):
    # Split the dataset
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

    # Create a RandomForestClassifier with varying n_estimators
    r = RandomForestClassifier(n_estimators=i)

    # Train the model
    r.fit(x_train, y_train)

    # Calculate training accuracy
    train_score = r.score(x_train, y_train)

    # Calculate testing accuracy
    test_score = r.score(x_test, y_test)

    # Update maximum training accuracy
    if train_score > max_train_accuracy:
        max_train_accuracy = train_score
        best_train_random_state = 42  # Since we're using a fixed random state for splitting

    # Update maximum testing accuracy
    if test_score > max_test_accuracy:
        max_test_accuracy = test_score
        best_test_random_state = 42  # Since we're using a fixed random state for splitting
        best_n_estimators = i

# Print results
print(f"The maximum training accuracy is: {max_train_accuracy} achieved with random state: {best_train_random_state}")
print(f"The maximum testing accuracy is: {max_test_accuracy} achieved with random state: {best_test_random_state} and n_estimators: {best_n_estimators}")


c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Pleas

The maximum training accuracy is: 1.0 achieved with random state: 42
The maximum testing accuracy is: 1.0 achieved with random state: 42 and n_estimators: 7


In [38]:
###
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

# Assuming 'x' and 'y' are defined with your dataset

max_train_accuracy = 0.0  # Initialize maximum training accuracy
best_train_random_state = 0  # Initialize variable to store the random state of the best training accuracy
max_test_accuracy = 0.0  # Initialize maximum testing accuracy
best_test_random_state = 0  # Initialize variable to store the random state of the best testing accuracy

for i in range(1, 100):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=i)
    r=RandomForestClassifier()
    r.fit(x_train,y_train)  # Train the model
    train_score = r.score(x_train, y_train)  # Calculate accuracy on the training set
    test_score = r.score(x_test, y_test)  # Calculate accuracy on the test set
    
    # Check for the maximum training accuracy
    if train_score > max_train_accuracy:
        max_train_accuracy = train_score
        best_train_random_state = i

    # Check for the maximum testing accuracy
    if test_score > max_test_accuracy:
        max_test_accuracy = test_score
        best_test_random_state = i

print(f"The maximum training accuracy within the range of random states is: {max_train_accuracy} achieved with random state: {best_train_random_state}")
print(f"The maximum testing accuracy within the range of random states is: {max_test_accuracy} achieved with random state: {best_test_random_state}")


c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Pleas

The maximum training accuracy within the range of random states is: 1.0 achieved with random state: 1
The maximum testing accuracy within the range of random states is: 1.0 achieved with random state: 10


c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
