In [1]:
from PIL import Image,ImageOps
from pandas import  *
from numpy import *
from seaborn import *
from matplotlib.pyplot import *
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import LabelEncoder

In [2]:
df=read_csv('breast-cancer-wisconsin.data')

In [3]:
df.head()

id   clump_thickness   unif_cell_size   unif_cell_shape  \
0  1000025                 5                1                 1   
1  1002945                 5                4                 4   
2  1015425                 3                1                 1   
3  1016277                 6                8                 8   
4  1017023                 4                1                 1   

    marg_adhesion   single_epith_cell_size  bare_nulei   bland_chrom  \
0               1                        2           1             3   
1               5                        7          10             3   
2               1                        2           2             3   
3               1                        3           4             3   
4               3                        2           1             3   

    norm_nucleoli   mitoses   class  
0               1         1       2  
1               2         1       2  
2               1         1       2  
3               7         1       2  
4               1         1       2

In [4]:
df=df.drop(['id'],axis=1)
df

clump_thickness   unif_cell_size   unif_cell_shape   marg_adhesion  \
0                   5                1                 1               1   
1                   5                4                 4               5   
2                   3                1                 1               1   
3                   6                8                 8               1   
4                   4                1                 1               3   
..                ...              ...               ...             ...   
694                 3                1                 1               1   
695                 2                1                 1               1   
696                 5               10                10               3   
697                 4                8                 6               4   
698                 4                8                 8               5   

      single_epith_cell_size  bare_nulei   bland_chrom   norm_nucleoli  \
0                          2           1             3               1   
1                          7          10             3               2   
2                          2           2             3               1   
3                          3           4             3               7   
4                          2           1             3               1   
..                       ...         ...           ...             ...   
694                        3           2             1               1   
695                        2           1             1               1   
696                        7           3             8              10   
697                        3           4            10               6   
698                        4           5            10               4   

      mitoses   class  
0           1       2  
1           1       2  
2           1       2  
3           1       2  
4           1       2  
..        ...     ...  
694         1       2  
695         1       2  
696         2       4  
697         1       4  
698         1       4  

[699 rows x 10 columns]

In [5]:
df=df[df[' bare_nulei'] != '?']

In [6]:
x=df.iloc[: , 0:9]
y=df.iloc[: ,  9]

In [7]:
x

clump_thickness   unif_cell_size   unif_cell_shape   marg_adhesion  \
0                   5                1                 1               1   
1                   5                4                 4               5   
2                   3                1                 1               1   
3                   6                8                 8               1   
4                   4                1                 1               3   
..                ...              ...               ...             ...   
694                 3                1                 1               1   
695                 2                1                 1               1   
696                 5               10                10               3   
697                 4                8                 6               4   
698                 4                8                 8               5   

      single_epith_cell_size  bare_nulei   bland_chrom   norm_nucleoli  \
0                          2           1             3               1   
1                          7          10             3               2   
2                          2           2             3               1   
3                          3           4             3               7   
4                          2           1             3               1   
..                       ...         ...           ...             ...   
694                        3           2             1               1   
695                        2           1             1               1   
696                        7           3             8              10   
697                        3           4            10               6   
698                        4           5            10               4   

      mitoses  
0           1  
1           1  
2           1  
3           1  
4           1  
..        ...  
694         1  
695         1  
696         2  
697         1  
698         1  

[683 rows x 9 columns]

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=393)

In [9]:
from sklearn.linear_model import LogisticRegression
l=LogisticRegression()

In [10]:
l.fit(x_train,y_train)

LogisticRegression()

In [11]:
l.score(x_train,y_train)

0.9615384615384616

In [12]:
l.score(x_test,y_test) # YES, AGAIN IT'S A PERFECT MODEL. WOW!!!!!!!!

1.0

In [13]:
l.predict([[4,2,1,1,1,2,3,2,1]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([2], dtype=int64)

In [14]:
l.predict([[8,10,10,8,7,10,9,7,1]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([4], dtype=int64)

S  V  C

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=5)

In [16]:
from sklearn.svm import SVC
s=SVC(kernel='poly')             
s.fit(x_train,y_train)

SVC(kernel='poly')

In [17]:
s.score(x_train,y_train)

0.9743589743589743

In [18]:
s.score(x_test,y_test)       # 99% accuracy coool!

0.9927007299270073

In [19]:
l.predict([[8,10,10,8,7,10,9,7,1]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([4], dtype=int64)

In [20]:
l.predict([[4,2,1,1,1,2,3,2,1]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([2], dtype=int64)

........................................................................

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=129)

In [22]:
from sklearn.svm import SVC
s=SVC(kernel='linear')             
s.fit(x_train,y_train)

SVC(kernel='linear')

In [23]:
s.score(x_train,y_train)

0.967032967032967

In [24]:
s.score(x_test,y_test)   # poly better fits here.

1.0

In [61]:
s.predict([[8,10,10,8,7,10,9,7,1]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([4], dtype=int64)

In [64]:
from sklearn.ensemble import RandomForestClassifier
r=RandomForestClassifier(n_estimators=60,random_state=1)
r.fit(x_train,y_train)

RandomForestClassifier(n_estimators=60, random_state=1)

U may change n_estimators to 50 or 100, but it causes overfitting on train data

10 is best(99% accuracy)

In [65]:
r.score(x_train,y_train)

1.0

In [66]:
r.score(x_test,y_test)

0.9927007299270073

In [67]:
r.predict([[8,10,10,8,7,10,9,7,1]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([4], dtype=int64)

In [58]:
from sklearn.ensemble import GradientBoostingClassifier
g=GradientBoostingClassifier(n_estimators=50,random_state=1)
g.fit(x_train,y_train)

GradientBoostingClassifier(n_estimators=50, random_state=1)

In [59]:
g.score(x_train,y_train)

0.9908424908424909

In [60]:
g.score(x_test,y_test)

0.9854014598540146

In [63]:
g.predict([[8,10,10,8,7,10,9,7,1]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(


array([4], dtype=int64)

RF is best. Even better than Gradient Boosting

In [ ]:
'''import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# Assuming 'x' and 'y' are defined with your dataset

max_train_accuracy = 0.0  # Initialize maximum training accuracy
best_train_random_state = 0  # Initialize variable to store the random state of the best training accuracy
max_test_accuracy = 0.0  # Initialize maximum testing accuracy
best_test_random_state = 0  # Initialize variable to store the random state of the best testing accuracy

for i in range(1, 1000):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=i)
    l = LogisticRegression()  # Initialize your model here, for example, Logistic Regression
    l.fit(x_train, y_train)   # Train the model
    train_score = l.score(x_train, y_train)  # Calculate accuracy on the training set
    test_score = l.score(x_test, y_test)  # Calculate accuracy on the test set
    
    # Check for the maximum training accuracy
    if train_score > max_train_accuracy:
        max_train_accuracy = train_score
        best_train_random_state = i

    # Check for the maximum testing accuracy
    if test_score > max_test_accuracy:
        max_test_accuracy = test_score
        best_test_random_state = i

print(f"The maximum training accuracy within the range of random states is: {max_train_accuracy} achieved with random state: {best_train_random_state}")
print(f"The maximum testing accuracy within the range of random states is: {max_test_accuracy} achieved with random state: {best_test_random_state}")
'''

The maximum training accuracy within the range of random states is: 0.9853479853479854 achieved with random state: 61
The maximum testing accuracy within the range of random states is: 1.0 achieved with random state: 393


In [ ]:
###
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

# Assuming 'x' and 'y' are defined with your dataset

max_train_accuracy = 0.0  # Initialize maximum training accuracy
best_train_random_state = 0  # Initialize variable to store the random state of the best training accuracy
max_test_accuracy = 0.0  # Initialize maximum testing accuracy
best_test_random_state = 0  # Initialize variable to store the random state of the best testing accuracy

for i in range(1, 500):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=i)
    r=SVC(kernel='linear')
    r.fit(x_train,y_train)  # Train the model
    train_score = r.score(x_train, y_train)  # Calculate accuracy on the training set
    test_score = r.score(x_test, y_test)  # Calculate accuracy on the test set
    
    # Check for the maximum training accuracy
    if train_score > max_train_accuracy:
        max_train_accuracy = train_score
        best_train_random_state = i

    # Check for the maximum testing accuracy
    if test_score > max_test_accuracy:
        max_test_accuracy = test_score
        best_test_random_state = i

print(f"The maximum training accuracy within the range of random states is: {max_train_accuracy} achieved with random state: {best_train_random_state}")
print(f"The maximum testing accuracy within the range of random states is: {max_test_accuracy} achieved with random state: {best_test_random_state}")


The maximum training accuracy within the range of random states is: 0.9871794871794872 achieved with random state: 141
The maximum testing accuracy within the range of random states is: 1.0 achieved with random state: 129
