In [120]:
from pandas import  *
from seaborn import *
from matplotlib.pyplot import *
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import LabelEncoder

In [121]:
df=read_csv('diabetes.csv')
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [122]:
x=df.iloc[: , 0:8]
y=df['Outcome']

In [123]:
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [124]:
from sklearn.linear_model import LogisticRegression
l=LogisticRegression()
l.fit(x,y)

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

SEE ACCURACY W.R.T diabetes p2 in Logistic Reg(76%) is more by 2% .                 AND in KNN CLASSIFIER  accuracy is 79% .

In [125]:
l.score(x,y)  

0.7825520833333334

In [126]:
l.predict([[1,189,60,23,843,30,0.398,59]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [127]:
l.predict([[3,126,88,41,235,39.3,0.704,27]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [128]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=142)

In [129]:
r=LogisticRegression()
r.fit(x_train,y_train)

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [130]:
r.score(x_train,y_train)

0.758957654723127

In [131]:
r.score(x_test,y_test)     #test is more imp. / crucial than train accuracy

0.8636363636363636

IT'S OKAY. BUT NEED TO IMPROVE THE ACCUURACY . NO OVERFITTING ISSUE

In [132]:
l.predict([[3,126,88,41,235,39.3,0.704,27]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [133]:
l.predict([[1,189,60,23,843,30,0.398,59]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

S  V  C

In [134]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=82)

In [135]:
from sklearn.svm import SVC
s=SVC(kernel='poly')             
s.fit(x_train,y_train)

SVC(kernel='poly')

In [136]:
s.score(x_train,y_train)

0.750465549348231

In [137]:
s.score(x_test,y_test)       # 100% accuracy coool!

0.8268398268398268

In [138]:
'''#RF model
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

max_train_accuracy = 0  # Initialize maximum training accuracy
max_test_accuracy = 0  # Initialize maximum test accuracy
best_random_state_train = 0
best_random_state_test = 0

for i in range(1, 100):  # Vary random state
    # Vary number of estimators
    d = RandomForestRegressor(random_state=i)
    d.fit(x_train, y_train)
    
    train_accuracy = d.score(x_train, y_train)  # Evaluate accuracy on training data
    test_accuracy = d.score(x_test, y_test)  # Evaluate accuracy on test data
    
    # Check and update best training accuracy and random state
    if train_accuracy > max_train_accuracy:
        max_train_accuracy = train_accuracy
        best_random_state_train = i
    
    # Check and update best test accuracy and random state
    if test_accuracy > max_test_accuracy:
        max_test_accuracy = test_accuracy
        best_random_state_test = i

print(f"Best Training Accuracy: {max_train_accuracy} achieved with random state: {best_random_state_train}")
print(f"Best Test Accuracy: {max_test_accuracy} achieved with random state: {best_random_state_test}")
'''

'#RF model\nfrom sklearn.ensemble import RandomForestRegressor\nfrom sklearn.model_selection import train_test_split\n\nmax_train_accuracy = 0  # Initialize maximum training accuracy\nmax_test_accuracy = 0  # Initialize maximum test accuracy\nbest_random_state_train = 0\nbest_random_state_test = 0\n\nfor i in range(1, 100):  # Vary random state\n    # Vary number of estimators\n    d = RandomForestRegressor(random_state=i)\n    d.fit(x_train, y_train)\n    \n    train_accuracy = d.score(x_train, y_train)  # Evaluate accuracy on training data\n    test_accuracy = d.score(x_test, y_test)  # Evaluate accuracy on test data\n    \n    # Check and update best training accuracy and random state\n    if train_accuracy > max_train_accuracy:\n        max_train_accuracy = train_accuracy\n        best_random_state_train = i\n    \n    # Check and update best test accuracy and random state\n    if test_accuracy > max_test_accuracy:\n        max_test_accuracy = test_accuracy\n        best_random_sta

In [139]:
from sklearn.ensemble import RandomForestClassifier
r=RandomForestClassifier(random_state=1)
r.fit(x_train,y_train)

RandomForestClassifier(random_state=1)

In [140]:
r.score(x_train,y_train)

1.0

In [141]:
r.score(x_test,y_test)

0.8008658008658008

In [142]:
from sklearn.ensemble import RandomForestClassifier

# Instantiate the RandomForestClassifier
r = RandomForestClassifier(
    n_estimators=100,  # You can adjust the number of trees
    max_depth=200,  # Set max_depth to control the maximum depth of trees
    min_samples_split=5,  # Minimum number of samples required to split an internal node
    min_samples_leaf=6,   # Minimum number of samples required to be at a leaf node
    random_state=1  # Set a random state for reproducibility
)

# Train the model
r.fit(x_train, y_train)

# Make predictions
y_pred = r.predict(x_test)

# Evaluate the model



In [143]:
r.score(x_test,y_test)

0.7922077922077922

In [144]:
from sklearn.ensemble import GradientBoostingClassifier
g=GradientBoostingClassifier(n_estimators=250,random_state=1)
g.fit(x_train,y_train)

GradientBoostingClassifier(n_estimators=250, random_state=1)

In [145]:
g.score(x_train,y_train)

0.9888268156424581

In [146]:
g.score(x_test,y_test)

0.7748917748917749

In [147]:
from sklearn.ensemble import AdaBoostClassifier
a=AdaBoostClassifier(n_estimators=200,random_state=1)
a.fit(x_train,y_train)

AdaBoostClassifier(n_estimators=200, random_state=1)

In [148]:
a.score(x_train,y_train)

0.8789571694599627

In [149]:
a.score(x_test,y_test)

0.7619047619047619

In [150]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


In [161]:

# Standardize the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(x)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=1)


In [166]:

# Build the ANN model
model = Sequential()
model.add(Dense(units=4096, activation='relu', input_dim=8)) # Adjusted units based on problem complexity
model.add(Dense(units=2048, activation='relu'))
model.add(Dense(units=1024, activation='relu'))
model.add(Dense(units=512, activation='relu'))
model.add(Dense(units=256, activation='relu'))
model.add(Dense(units=128, activation='relu'))
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=16, activation='relu'))
model.add(Dense(units=1, activation='sigmoid'))  # Binary classification, so using sigmoid activation

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=20, batch_size=1, validation_data=(X_test, y_test))


Epoch 1/20
537/537 [==============================] - 44s 78ms/step - loss: 0.6484 - accuracy: 0.6592 - val_loss: 0.6603 - val_accuracy: 0.6320
Epoch 2/20
165/537 [========>.....................] - ETA: 26s - loss: 0.6216 - accuracy: 0.6970

KeyboardInterrupt: 

In [165]:

# Evaluate the model on the test set
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print("Test Set Loss:", test_loss)
print("Test Set Accuracy:", test_accuracy)


8/8 [==============================] - 0s 6ms/step - loss: 0.4982 - accuracy: 0.7706
Test Set Loss: 0.49821871519088745
Test Set Accuracy: 0.7705627679824829


In [ ]:

# Evaluate the model on the test set
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print("Test Set Loss:", test_loss)
print("Test Set Accuracy:", test_accuracy)


In [ ]:
#RF model
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

max_train_accuracy = 0  # Initialize maximum training accuracy
max_test_accuracy = 0  # Initialize maximum test accuracy
best_random_state_train = 0
best_random_state_test = 0

for i in range(1, 100):  # Vary random state
    # Vary number of estimators
    d = GradientBoostingClassifier(random_state=i)
    d.fit(x_train, y_train)
    
    train_accuracy = d.score(x_train, y_train)  # Evaluate accuracy on training data
    test_accuracy = d.score(x_test, y_test)  # Evaluate accuracy on test data
    
    # Check and update best training accuracy and random state
    if train_accuracy > max_train_accuracy:
        max_train_accuracy = train_accuracy
        best_random_state_train = i
    
    # Check and update best test accuracy and random state
    if test_accuracy > max_test_accuracy:
        max_test_accuracy = test_accuracy
        best_random_state_test = i

print(f"Best Training Accuracy: {max_train_accuracy} achieved with random state: {best_random_state_train}")
print(f"Best Test Accuracy: {max_test_accuracy} achieved with random state: {best_random_state_test}")


Best Training Accuracy: 0.9404096834264432 achieved with random state: 1
Best Test Accuracy: 0.7619047619047619 achieved with random state: 4


In [ ]:
'''import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# Assuming 'x' and 'y' are defined with your dataset

max_train_accuracy = 0.0  # Initialize maximum training accuracy
best_train_random_state = 0  # Initialize variable to store the random state of the best training accuracy
max_test_accuracy = 0.0  # Initialize maximum testing accuracy
best_test_random_state = 0  # Initialize variable to store the random state of the best testing accuracy

for i in range(1, 1000):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=i)
    l = LogisticRegression()  # Initialize your model here, for example, Logistic Regression
    l.fit(x_train, y_train)   # Train the model
    train_score = l.score(x_train, y_train)  # Calculate accuracy on the training set
    test_score = l.score(x_test, y_test)  # Calculate accuracy on the test set
    
    # Check for the maximum training accuracy
    if train_score > max_train_accuracy:
        max_train_accuracy = train_score
        best_train_random_state = i

    # Check for the maximum testing accuracy
    if test_score > max_test_accuracy:
        max_test_accuracy = test_score
        best_test_random_state = i

print(f"The maximum training accuracy within the range of random states is: {max_train_accuracy} achieved with random state: {best_train_random_state}")
print(f"The maximum testing accuracy within the range of random states is: {max_test_accuracy} achieved with random state: {best_test_random_state}")
'''

'import numpy as np\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.linear_model import LogisticRegression\n\n# Assuming \'x\' and \'y\' are defined with your dataset\n\nmax_train_accuracy = 0.0  # Initialize maximum training accuracy\nbest_train_random_state = 0  # Initialize variable to store the random state of the best training accuracy\nmax_test_accuracy = 0.0  # Initialize maximum testing accuracy\nbest_test_random_state = 0  # Initialize variable to store the random state of the best testing accuracy\n\nfor i in range(1, 1000):\n    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=i)\n    l = LogisticRegression()  # Initialize your model here, for example, Logistic Regression\n    l.fit(x_train, y_train)   # Train the model\n    train_score = l.score(x_train, y_train)  # Calculate accuracy on the training set\n    test_score = l.score(x_test, y_test)  # Calculate accuracy on the test set\n    \n    # Check for the maximum 

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

# Assuming 'x' and 'y' are defined with your dataset

max_train_accuracy = 0.0  # Initialize maximum training accuracy
best_train_random_state = 0  # Initialize variable to store the random state of the best training accuracy
max_test_accuracy = 0.0  # Initialize maximum testing accuracy
best_test_random_state = 0  # Initialize variable to store the random state of the best testing accuracy

for i in range(1, 500):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=i)
    r=SVC(kernel='poly')
    r.fit(x_train,y_train)  # Train the model
    train_score = r.score(x_train, y_train)  # Calculate accuracy on the training set
    test_score = r.score(x_test, y_test)  # Calculate accuracy on the test set
    
    # Check for the maximum training accuracy
    if train_score > max_train_accuracy:
        max_train_accuracy = train_score
        best_train_random_state = i

    # Check for the maximum testing accuracy
    if test_score > max_test_accuracy:
        max_test_accuracy = test_score
        best_test_random_state = i
  
print(f"The maximum training accuracy within the range of random states is: {max_train_accuracy} achieved with random state: {best_train_random_state}")
print(f"The maximum testing accuracy within the range of random states is: {max_test_accuracy} achieved with random state: {best_test_random_state}")


The maximum training accuracy within the range of random states is: 0.8119180633147114 achieved with random state: 24
The maximum testing accuracy within the range of random states is: 0.8268398268398268 achieved with random state: 82
