In [1]:

from pandas import  *
from numpy import *
from seaborn import *
from matplotlib.pyplot import *
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import LabelEncoder

In [2]:
df=read_csv('salaries.csv')
df

company              job     degree  salary_more_than_100k
0      amazon  project manager  bachelors                      1
1      amazon  project manager    masters                      1
2      amazon  sales executive  bachelors                      0
3      amazon  sales executive    masters                      0
4      amazon       programmer  bachelors                      0
5      amazon       programmer    masters                      1
6   jp morgan  sales executive    masters                      0
7   jp morgan       programmer  bachelors                      0
8   jp morgan  project manager  bachelors                      0
9   jp morgan  project manager    masters                      1
10  microsoft  sales executive  bachelors                      1
11  microsoft  sales executive    masters                      1
12  microsoft  project manager  bachelors                      1
13  microsoft  project manager    masters                      1
14  microsoft       programmer  bachelors                      1
15  microsoft       programmer    masters                      1

In [3]:
from sklearn.preprocessing import LabelEncoder

# Assuming 'df' is your dfFrame containing the columns 'company', 'job', 'degree'
# Create LabelEncoder objects for each column
label_encoder_company = LabelEncoder()
label_encoder_job = LabelEncoder()
label_encoder_degree = LabelEncoder()

# Fit label encoder and transform the categorical columns to numerical values
df['company'] = label_encoder_company.fit_transform(df['company'])
df['job'] = label_encoder_job.fit_transform(df['job'])
df['degree'] = label_encoder_degree.fit_transform(df['degree'])


In [4]:
df

company  job  degree  salary_more_than_100k
0         0    1       0                      1
1         0    1       1                      1
2         0    2       0                      0
3         0    2       1                      0
4         0    0       0                      0
5         0    0       1                      1
6         1    2       1                      0
7         1    0       0                      0
8         1    1       0                      0
9         1    1       1                      1
10        2    2       0                      1
11        2    2       1                      1
12        2    1       0                      1
13        2    1       1                      1
14        2    0       0                      1
15        2    0       1                      1

In [5]:
x=df.iloc[: , 0:3]
y=df['salary_more_than_100k']

In [6]:
x

company  job  degree
0         0    1       0
1         0    1       1
2         0    2       0
3         0    2       1
4         0    0       0
5         0    0       1
6         1    2       1
7         1    0       0
8         1    1       0
9         1    1       1
10        2    2       0
11        2    2       1
12        2    1       0
13        2    1       1
14        2    0       0
15        2    0       1

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=234)

In [8]:
from sklearn.linear_model import LogisticRegression
l=LogisticRegression()

In [9]:
l.fit(x_train,y_train)

LogisticRegression()

In [10]:
l.score(x_train,y_train)

0.7272727272727273

In [11]:
l.score(x_test,y_test)

1.0

In [12]:
l.predict([[1,1,0]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [13]:
l.predict([[2,0,0]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [14]:
l.predict([[0,0,0]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=41)

In [16]:
from sklearn.svm import SVC
s=SVC(kernel='rbf')             #  or, SVC()
s.fit(x_train,y_train)

SVC()

In [17]:
s.score(x_train,y_train)

1.0

In [18]:
s.score(x_test,y_test)       # 100% accuracy coool!

1.0

In [19]:
s.predict([[2,0,0]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [49]:
from sklearn.ensemble import RandomForestClassifier
r=RandomForestClassifier(n_estimators=100,random_state=32)
r.fit(x_train,y_train)

RandomForestClassifier(random_state=32)

In [50]:
r.score(x_train,y_train)

1.0

In [51]:
r.score(x_test,y_test)

1.0

In [52]:
r.predict([[2,0,0]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [48]:
#RF model
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

max_train_accuracy = 0  # Initialize maximum training accuracy
max_test_accuracy = 0  # Initialize maximum test accuracy
best_random_state_train = 0
best_random_state_test = 0

for i in range(1, 100):  # Vary random state
    # Vary number of estimators
    d = RandomForestClassifier(n_estimators=100,random_state=i)
    d.fit(x_train, y_train)
    
    train_accuracy = d.score(x_train, y_train)  # Evaluate accuracy on training data
    test_accuracy = d.score(x_test, y_test)  # Evaluate accuracy on test data
    
    # Check and update best training accuracy and random state
    if train_accuracy > max_train_accuracy:
        max_train_accuracy = train_accuracy
        best_random_state_train = i
    
    # Check and update best test accuracy and random state
    if test_accuracy > max_test_accuracy:
        max_test_accuracy = test_accuracy
        best_random_state_test = i

print(f"Best Training Accuracy: {max_train_accuracy} achieved with random state: {best_random_state_train}")
print(f"Best Test Accuracy: {max_test_accuracy} achieved with random state: {best_random_state_test}")


Best Training Accuracy: 1.0 achieved with random state: 1
Best Test Accuracy: 1.0 achieved with random state: 32


In [22]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

# Assuming 'x' and 'y' are defined with your dataset

max_train_accuracy = 0.0  # Initialize maximum training accuracy
best_train_random_state = 0  # Initialize variable to store the random state of the best training accuracy
max_test_accuracy = 0.0  # Initialize maximum testing accuracy
best_test_random_state = 0  # Initialize variable to store the random state of the best testing accuracy

for i in range(1, 1000):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=i)
    r=SVC()
    r.fit(x_train,y_train)  # Train the model
    train_score = r.score(x_train, y_train)  # Calculate accuracy on the training set
    test_score = r.score(x_test, y_test)  # Calculate accuracy on the test set
    
    # Check for the maximum training accuracy
    if train_score > max_train_accuracy:
        max_train_accuracy = train_score
        best_train_random_state = i

    # Check for the maximum testing accuracy
    if test_score > max_test_accuracy:
        max_test_accuracy = test_score
        best_test_random_state = i

print(f"The maximum training accuracy within the range of random states is: {max_train_accuracy} achieved with random state: {best_train_random_state}")
print(f"The maximum testing accuracy within the range of random states is: {max_test_accuracy} achieved with random state: {best_test_random_state}")


The maximum training accuracy within the range of random states is: 1.0 achieved with random state: 2
The maximum testing accuracy within the range of random states is: 1.0 achieved with random state: 41
