In [49]:
from pandas import  *
from seaborn import *
from matplotlib.pyplot import *
from sklearn.linear_model import LinearRegression

In [50]:
df=read_csv('carprices.csv')
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [51]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [52]:
df['Car Model']=le.fit_transform(df['Car Model'])

In [53]:
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5

In [54]:
x=(df[['Car Model'	, 'Mileage','Age(yrs)']])
y=(df[['Sell Price($)']])

In [55]:
r=LinearRegression()
r.fit(x,y)
r.score(x,y)

0.8719970367825952

In [56]:
r.predict([[1,35000,3]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[36101.34690856]])

In [57]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=465)

In [58]:
l=LinearRegression()
l.fit(x_train,y_train)

LinearRegression()

In [59]:
l.score(x_train,y_train)

0.7239532540025527

In [60]:
l.score(x_test,y_test)

0.9881648610436133

In [61]:
l.predict([[1,35000,3]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[36410.57467946]])

Both models before and after train- test split almost same error

In [71]:
from sklearn.preprocessing import PolynomialFeatures
r2=PolynomialFeatures(degree=2)# degree=2 is best for lower milage(calculated)
x2=r2.fit_transform(x)     #degree 5 is best gor higher milage

In [72]:
l=LinearRegression()
l.fit(x2,y)


LinearRegression()

In [73]:
l.score(x2,y)

0.9831414882399158

PREDICT PRICE OF CAR BY INPUT - 'carmodel' , 'mileage' , 'age'



FOR CAR MODEL- 
0  { Audi A5 }                 1   [ BMWX5 ]                 2  { Mercedez Benz C class }
             

In [74]:
l.predict(r2.fit_transform([[1,47000,4]]))

array([[30286.82400861]])

In [75]:
l.predict(r2.fit_transform([[1,35000,3]]))

array([[35500.55353947]])

In [66]:
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5

In [67]:
l.predict(r2.fit_transform([[1,70000,4]]))

array([[40751.903675]])

In [68]:
l.predict(r2.fit_transform([[2,25000,2]]))

array([[44214.89357658]])

In [69]:
###
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

# Assuming 'x' and 'y' are defined with your dataset

max_train_accuracy = 0.0  # Initialize maximum training accuracy
best_train_random_state = 0  # Initialize variable to store the random state of the best training accuracy
max_test_accuracy = 0.0  # Initialize maximum testing accuracy
best_test_random_state = 0  # Initialize variable to store the random state of the best testing accuracy

for i in range(465, 1100):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=i)
    r=LinearRegression()
    r.fit(x_train,y_train)  # Train the model
    train_score = r.score(x_train, y_train)  # Calculate accuracy on the training set
    test_score = r.score(x_test, y_test)  # Calculate accuracy on the test set
    
    # Check for the maximum training accuracy
    if train_score > max_train_accuracy:
        max_train_accuracy = train_score
        best_train_random_state = i

    # Check for the maximum testing accuracy
    if test_score > max_test_accuracy:
        max_test_accuracy = test_score
        best_test_random_state = i

print(f"The maximum training accuracy within the range of random states is: {max_train_accuracy} achieved with random state: {best_train_random_state}")
print(f"The maximum testing accuracy within the range of random states is: {max_test_accuracy} achieved with random state: {best_test_random_state}")


The maximum training accuracy within the range of random states is: 0.9641203677505334 achieved with random state: 734
The maximum testing accuracy within the range of random states is: 0.9881648610436133 achieved with random state: 465
